# Generated by Django 5.2.6 on 2025-10-01 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='The question being asked', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this question was published', verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Poll Question',
                'verbose_name_plural': 'Poll Questions',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='The choice text', max_length=200)),
                ('votes', models.IntegerField(default=0, help_text='Number of votes for this choice')),
                ('question', models.ForeignKey(help_text='The question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'verbose_name': 'Poll Choice',
                'verbose_name_plural': 'Poll Choices',
                'ordering': ['-votes', 'choice_text'],
            },
        ),
    ]
